image: Visual Studio 2017

environment:
    matrix:
        - GENERATOR: "Visual Studio 15 2017 Win64"
          QTDIR: C:\Qt\5.12\msvc2017_64
        - GENERATOR: "Visual Studio 15 2017"
          QTDIR: C:\Qt\5.12\msvc2017

configuration: Release

install:
    - set PATH=%QTDIR%\bin;%PATH%

before_build:
    - mkdir build
    - cd build
    - cmake "-G%GENERATOR%" "-DBUILD_CLI=ON" ..

build_script:
    - cmake --build . --config Release

test_script:
    - ctest --config Release --output-on-failure
