image: Visual Studio 2017

environment:
    matrix:
        - arch: x64
          GENERATOR: "Visual Studio 15 2017 Win64"
          QTDIR: C:\Qt\5.12\msvc2017_64
        - arch: x86
          GENERATOR: "Visual Studio 15 2017"
          QTDIR: C:\Qt\5.12\msvc2017

configuration: Release

install:
    - set PATH=%QTDIR%\bin;%PATH%

before_build:
    - mkdir build
    - cd build
    - cmake "-G%GENERATOR%" "-DBUILD_CLI=ON" ..

build_script:
    - cmake --build . --config Release

#test_script:
#    - ctest -C Release --output-on-failure

after_build:
    - mkdir deploy
    - cmd: pwd
    - cmd: cp Release/Grate.exe deploy/Grate.exe
    - windeployqt deploy/Grate.exe
    - 7z a Grate_win_%arch%.zip .\deploy\*

artifacts:
    - path: build/Grate_win_%arch%.zip

deploy:
    description: "GRATE release"
    provider: GitHub
    auth_token:
        secure: 6tycvfuSfg+VL9ZMqF0Os1kUjGQ24o5AyOzQZc8eFGkdaKtBVRQWkL4f3IE5gH1r
    artifact: build/Grate_win_%arch%.zip
    draft: false
    prerelease: false
    on:
        APPVEYOR_REPO_TAG: true
