image: Visual Studio 2017

environment:
    matrix:
        - arch: x64
          GENERATOR: "Visual Studio 15 2017 Win64"
          QTDIR: C:\Qt\5.12\msvc2017_64
        - arch: x86
          GENERATOR: "Visual Studio 15 2017"
          QTDIR: C:\Qt\5.12\msvc2017

configuration: Release

install:
    - choco install -y InnoSetup
    - set PATH=%QTDIR%\bin;%PATH%

before_build:
    - mkdir build
    - cd build
    - cmake "-G%GENERATOR%" "-DBUILD_CLI=ON" ..

build_script:
    - cmake --build . --config Release

#test_script:
#    - ctest -C Release --output-on-failure

after_build:
    - mkdir deploy
    - cmd: cp build/Release/GrateRip.exe deploy/GrateRip.exe
    - windeployqt build/Release/GrateRip.exe
    - 7z a GrateRip_win_%arch%.zip .\deploy\*

artifacts:
    - path: GrateRip_win_%arch%.zip
