sudo: required
dist: trusty
language: cpp


before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - sudo apt-get update -q
    - sudo apt-get install cmake qt5-default gcc-8 g++-8 -y
    - type qmake
    - type cmake
    - type gcc-8
    - type g++-8
    - export CC=gcc-8
    - export CXX=g++-8
    - ${CXX} --version

install:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
    - make VERBOSE=1

script:
    - ctest --output-on-failure
