language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
        - os: osx
          addons:
              homebrew:
                  packages:
                      - cmake
                      - qt

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get update -q
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get install cmake gcc-8 g++-8 qt511-meta-minimal -y
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then source /opt/qt511/bin/qt511-env.sh
    - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then qmake --version
    - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then cmake --version
    - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then export CC=gcc-8
    - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then export CXX=g++-8
    - ${CXX} --version

install:
    - mkdir build && cd build
    - cmake ..
    - make

script:
    - echo "not running any tests"
#    - ctest --output-on-failure
