language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
        - os: osx
          addons:
              homebrew:
                  packages:
                      - cmake
                      - qt
                  update: true

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -q; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc-9 g++-9 qt511-meta-minimal libgl1-mesa-dev -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt511/bin/qt511-env.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake --version; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake --version; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-9; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-9; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"; fi
    - ${CXX} --version

install:
    - mkdir build && cd build
    - cmake ..
    - make
    - pwd

script:
    - echo "not running any tests"
#    - ctest --output-on-failure

before_deploy:
    - pwd
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir -p Grate.app/Contents/PlugIns/platforms; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp "$(brew --prefix)/opt/qt/plugins/platforms/libqcocoa.dylib" Grate.app/Contents/PlugIns/platforms/; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt Grate.app -dmg; fi
    - ls -l

deploy:
    provider: releases
    api_key:
        secure: V4U8kv/O3OsYs8oVUIEVWH/AG/pxCv5tf1J59eonb+PqrEOt2IA9lnufysC2JoOW73sQswWy0y2w/IwH9NMkg+dzI9ZEV8B084M1+gzYafON+tuG9r7vxWgeSmx77HR59myD91S8Ip3+siFnjXPuqN+BPyGm+EVq4Y0HgS3bAt7O4QV3fwPTym0Enm40T7WNxRltcmYjw63vX098xgD2c+gb62W/4upQ3MFaXIU+B2CKyQr5vD/zgbAdOpZdiFdFDXdq7nY/qWegoRUYEVmlx1g2s+nhAzkc50oHcF8X6MMDSzjTWuUlSnfGXXPlS7yNW55+rWJnaB3wLv5qVqX29GbyV8+Z58o6iHtbxcdENhEX1SRuUDsYMeJ6NzqNO65TKJ3EkjSgB31ofjthjwQ6JaP0pz32oKcW5WgDZPKizw+4j/tpzue+xQg8nz1AzNxz3cJ9NYdWqjBOqtrHOLV+nZZZio15sqN2AkdABvp65HVQv2UotdUDmC+thpXTRwNVr4PP6YjqrilYTxRAXIjWR5MXHkyVeDuW6113KxxgExBs69z2ixdZzLqdDev837LyWqD62vTcWtwYqSGy7HVs548DcRyelJM1I23wKIsqjQiz71VxCw2XXecr80AC4nPWLwNLaCz6pQyRSH9utDagM9LX+c5YDniyCHj1b/bzbps=
    file: Grate.dmg
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_OS_NAME = osx
