language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
        - os: osx
          addons:
              homebrew:
                  packages:
                      - cmake
                      - qt
                  update: true

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -q; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc-9 g++-9 qt511-meta-minimal libgl1-mesa-dev -y; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt511/bin/qt511-env.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake --version; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake --version; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC=gcc-9; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-9; fi
    - ${CXX} --version

install:
    - mkdir build && cd build
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake ..; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix)/opt/qt"; fi
    - make

script:
    - echo "not running any tests"
#    - ctest --output-on-failure
